In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
PATH = 'data/'

In [3]:
products = pd.read_csv(f'{PATH}amazon_baby_subset.csv')

In [5]:
products

name  \
0      Stop Pacifier Sucking without tears with Thumb...   
1        Nature's Lullabies Second Year Sticker Calendar   
2        Nature's Lullabies Second Year Sticker Calendar   
3                            Lamaze Peekaboo, I Love You   
4      SoftPlay Peek-A-Boo Where's Elmo A Children's ...   
...                                                  ...   
53067  Samsung Baby Care Washer, Stainless Platinum, ...   
53068                    Mud Pie Milestone Stickers, Boy   
53069       Best BIB for Baby - Soft Bib (Pink-Elephant)   
53070       Bouncy&reg; Inflatable Real Feel Hopping Cow   
53071  Maxboost iPhone 5S/5 Case - Protective Snap-on...   

                                                  review  rating  sentiment  
0      All of my kids have cried non-stop when I trie...       5          1  
1      We wanted to get something to keep track of ou...       5          1  
2      My daughter had her 1st baby over a year ago. ...       5          1  
3      One of baby's first and favorite books, and it...       4          1  
4      Very cute interactive book! My son loves this ...       5          1  
...                                                  ...     ...        ...  
53067  My infant goes to a really crappy daycare, and...       1         -1  
53068  Pretty please open and inspect these stickers ...       1         -1  
53069  Great 5-Star Product but An Obvious knock-off ...       1         -1  
53070  When I received the item my initial thought wa...       2         -1  
53071  I got this case in the mail today, it came on ...       2         -1  

[53072 rows x 4 columns]

### The following are the first 10 names

In [14]:
products.head(10)

name  \
0  Stop Pacifier Sucking without tears with Thumb...   
1    Nature's Lullabies Second Year Sticker Calendar   
2    Nature's Lullabies Second Year Sticker Calendar   
3                        Lamaze Peekaboo, I Love You   
4  SoftPlay Peek-A-Boo Where's Elmo A Children's ...   
5                          Our Baby Girl Memory Book   
6  Hunnt&reg; Falling Flowers and Birds Kids Nurs...   
7  Blessed By Pope Benedict XVI Divine Mercy Full...   
8  Cloth Diaper Pins Stainless Steel Traditional ...   
9  Cloth Diaper Pins Stainless Steel Traditional ...   

                                              review  rating  sentiment  
0  All of my kids have cried non-stop when I trie...       5          1  
1  We wanted to get something to keep track of ou...       5          1  
2  My daughter had her 1st baby over a year ago. ...       5          1  
3  One of baby's first and favorite books, and it...       4          1  
4  Very cute interactive book! My son loves this ...       5          1  
5  Beautiful book, I love it to record cherished ...       5          1  
6  Try this out for a spring project !Easy ,fun a...       5          1  
7  very nice Divine Mercy Pendant of Jesus now on...       5          1  
8  We bought the pins as my 6 year old Autistic s...       4          1  
9  It has been many years since we needed diaper ...       5          1

### 26579 reviews are positive

In [11]:
products[products['sentiment'] == 1]

name  \
0      Stop Pacifier Sucking without tears with Thumb...   
1        Nature's Lullabies Second Year Sticker Calendar   
2        Nature's Lullabies Second Year Sticker Calendar   
3                            Lamaze Peekaboo, I Love You   
4      SoftPlay Peek-A-Boo Where's Elmo A Children's ...   
...                                                  ...   
26574  Maxboost iPhone 5S/5 Case - Protective Snap-on...   
26575  Maxboost iPhone 5S/5 Case - Protective Snap-on...   
26576  Airline Seat Belt Extender - The Best Extensio...   
26577  Squeasy Snacker 6oz Silicone Reusable Food Pou...   
26578  Baby Food Freezer Tray - Bacteria Resistant, B...   

                                                  review  rating  sentiment  
0      All of my kids have cried non-stop when I trie...       5          1  
1      We wanted to get something to keep track of ou...       5          1  
2      My daughter had her 1st baby over a year ago. ...       5          1  
3      One of baby's first and favorite books, and it...       4          1  
4      Very cute interactive book! My son loves this ...       5          1  
...                                                  ...     ...        ...  
26574  got this for my wife and she loves it would de...       5          1  
26575  this case is the greatest very cool and stylis...       5          1  
26576  I bought this as a father's day gift for my da...       5          1  
26577  This reusable squeeze bottle is the best I hav...       5          1  
26578  I am extremely happy with this product. I have...       5          1  

[26579 rows x 4 columns]

### 26493 reviews are negative

In [13]:
products[products['sentiment'] == -1]

name  \
26579    Nature's Lullabies Second Year Sticker Calendar   
26580         SoftPlay Giggle Jiggle Funbook, Happy Bear   
26581                          SoftPlay Cloth Book, Love   
26582  Hunnt&reg; Falling Flowers and Birds Kids Nurs...   
26583  Wall Decor Removable Decal Sticker - Colorful ...   
...                                                  ...   
53067  Samsung Baby Care Washer, Stainless Platinum, ...   
53068                    Mud Pie Milestone Stickers, Boy   
53069       Best BIB for Baby - Soft Bib (Pink-Elephant)   
53070       Bouncy&reg; Inflatable Real Feel Hopping Cow   
53071  Maxboost iPhone 5S/5 Case - Protective Snap-on...   

                                                  review  rating  sentiment  
26579  I only purchased a second-year calendar for my...       2         -1  
26580  This bear is absolutely adorable and I would g...       2         -1  
26581  This book is boring. Nothing to stimulate my g...       1         -1  
26582  The reason:Small sizeHard to apply on the wall...       1         -1  
26583  Would not purchase again or recommend. The dec...       2         -1  
...                                                  ...     ...        ...  
53067  My infant goes to a really crappy daycare, and...       1         -1  
53068  Pretty please open and inspect these stickers ...       1         -1  
53069  Great 5-Star Product but An Obvious knock-off ...       1         -1  
53070  When I received the item my initial thought wa...       2         -1  
53071  I got this case in the mail today, it came on ...       2         -1  

[26493 rows x 4 columns]

In [16]:
products = products.fillna({'review':''})

In [17]:
def remove_punctuation(text):
    import string
    return text.translate(str.maketrans('', '', string.punctuation)) 

products['review_clean'] = products['review'].apply(remove_punctuation)

In [18]:
import json
f = open(f'{PATH}important_words.json')
important_words = json.load(f)
f.close()

In [21]:
for word in important_words:
    products[word] = products['review_clean'].apply(lambda s : s.split().count(word))

In [24]:
def word_checker(num):
    if num > 0: 
        return 1
    return 0

In [25]:
products['contains_perfect'] = products['perfect'].apply(word_checker)

In [27]:
products['contains_perfect'].sum()

2955

### 2955 reviews contain the word perfect

In [30]:
def get_numpy_data(df,features,label):
    df['constant'] = 1
    features = ['constant'] + features
    features_frame = df[features]
    features_matrix = features_frame.to_numpy()
    label_series = df[label]
    label_array = label_series.to_numpy()
    return features_matrix,label_array

In [31]:
features_matrix,label_array = get_numpy_data(products,important_words,'sentiment')

In [32]:
features_matrix

array([[1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [1, 1, 0, ..., 0, 0, 0],
       ...,
       [1, 0, 0, ..., 0, 0, 0],
       [1, 0, 1, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [33]:
label_array

array([ 1,  1,  1, ..., -1, -1, -1], dtype=int64)

In [36]:
features_matrix.shape

(53072, 194)

### There are 194 features in the features matrix

### Number of features in the features matrix is equal to the number of features in the logistic regression model

In [43]:
'''
produces probablistic estimate for P(y_i = +1 | x_i, w).
estimate ranges between 0 and 1.
'''
def predict_probability(feature_matrix, coefficients):
    # Take dot product of feature_matrix and coefficients  
    # YOUR CODE HERE
    score = np.dot(feature_matrix, coefficients)
    
    # Compute P(y_i = +1 | x_i, w) using the link function
    # YOUR CODE HERE
    predictions = 1 / (1 + np.exp(-score))
    
    # return predictions
    return predictions

In [44]:
def feature_derivative(errors, feature):     
    # Compute the dot product of errors and feature
    derivative = np.dot(feature,errors)
        # Return the derivative
    return derivative

In [47]:
def compute_log_likelihood(feature_matrix, sentiment, coefficients):
    indicator = (sentiment==+1)
    scores = np.dot(feature_matrix, coefficients)
    lp = np.sum((indicator-1)*scores - np.log(1. + np.exp(-scores)))
    return lp

In [49]:
from math import sqrt
def logistic_regression(feature_matrix, sentiment, initial_coefficients, step_size, max_iter):
    coefficients = np.array(initial_coefficients) # make sure it's a numpy array
    for itr in range(max_iter):
        # Predict P(y_i = +1|x_1,w) using your predict_probability() function
        # YOUR CODE HERE
        predictions = predict_probability(features_matrix,coefficients)

        # Compute indicator value for (y_i = +1)
        indicator = (sentiment==+1)

        # Compute the errors as indicator - predictions
        errors = indicator - predictions

        for j in range(len(coefficients)): # loop over each coefficient
            # Recall that feature_matrix[:,j] is the feature column associated with coefficients[j]
            # compute the derivative for coefficients[j]. Save it in a variable called derivative
            # YOUR CODE HERE
            derivative = feature_derivative(errors,feature_matrix[:,j])

            # add the step size times the derivative to the current coefficient
            # YOUR CODE HERE
            coefficients[j] += step_size*derivative 

        # Checking whether log likelihood is increasing
        if itr <= 15 or (itr <= 100 and itr % 10 == 0) or (itr <= 1000 and itr % 100 == 0) \
        or (itr <= 10000 and itr % 1000 == 0) or itr % 10000 == 0:
            lp = compute_log_likelihood(feature_matrix, sentiment, coefficients)
            print('iteration %*d: log likelihood of observed labels = %.8f' % \
                (int(np.ceil(np.log10(max_iter))), itr, lp))
    return coefficients

In [52]:
coefficients = logistic_regression(features_matrix,label_array,np.zeros(194),1e-7,301)

iteration   0: log likelihood of observed labels = -36780.91768478
iteration   1: log likelihood of observed labels = -36775.13434712
iteration   2: log likelihood of observed labels = -36769.35713564
iteration   3: log likelihood of observed labels = -36763.58603240
iteration   4: log likelihood of observed labels = -36757.82101962
iteration   5: log likelihood of observed labels = -36752.06207964
iteration   6: log likelihood of observed labels = -36746.30919497
iteration   7: log likelihood of observed labels = -36740.56234821
iteration   8: log likelihood of observed labels = -36734.82152213
iteration   9: log likelihood of observed labels = -36729.08669961
iteration  10: log likelihood of observed labels = -36723.35786366
iteration  11: log likelihood of observed labels = -36717.63499744
iteration  12: log likelihood of observed labels = -36711.91808422
iteration  13: log likelihood of observed labels = -36706.20710739
iteration  14: log likelihood of observed labels = -36700.5020

In [54]:
def threshold(x):
    if x > 0: 
        return 1
    return -1

In [59]:
predictions = np.dot(features_matrix,coefficients)

In [60]:
predictions

array([ 0.05104571, -0.02936473,  0.02411584, ..., -0.40986295,
        0.01411436, -0.06755923])

In [72]:
(predictions == 1).sum()

25126

### 25126 reviews were predicted to have positive sentiment

In [62]:
for i in range(len(predictions)):
    if(predictions[i]) > 0:
        predictions[i] = 1
    else:
        predictions[i] = -1

In [63]:
predictions

array([ 1., -1.,  1., ..., -1.,  1., -1.])

In [65]:
len(predictions)

53072

In [66]:
(predictions == label_array).sum() / len(predictions)

0.7518653904130238

### Accuracy of the model on the predictions made above is 0.75

In [67]:
coefficients = list(coefficients[1:]) # exclude intercept
word_coefficient_tuples = [(word, coefficient) for word, coefficient in zip(important_words, coefficients)]
word_coefficient_tuples = sorted(word_coefficient_tuples, key=lambda x:x[1], reverse=True)

In [68]:
word_coefficient_tuples

[('great', 0.0665460841704577),
 ('love', 0.06589076292212326),
 ('easy', 0.06479458680257838),
 ('little', 0.045435626308421365),
 ('loves', 0.04497640139490604),
 ('well', 0.030135001092107077),
 ('perfect', 0.029739937104968462),
 ('old', 0.020077541034775378),
 ('nice', 0.018408707995268992),
 ('daughter', 0.017703199905701694),
 ('soft', 0.01757027224560289),
 ('fits', 0.01688247107140872),
 ('happy', 0.01680529588976808),
 ('baby', 0.015565696580423507),
 ('recommend', 0.015408450108008665),
 ('also', 0.015216196422918844),
 ('best', 0.014991791565630264),
 ('comfortable', 0.0132539900815849),
 ('car', 0.012685935745813375),
 ('clean', 0.012018174433365525),
 ('son', 0.011944817713693955),
 ('bit', 0.011708248093123262),
 ('works', 0.011703160621987424),
 ('size', 0.010715966516270301),
 ('stroller', 0.009909164635972736),
 ('room', 0.009783241021568061),
 ('price', 0.009572733543590181),
 ('play', 0.00917842898398431),
 ('easily', 0.009032818138954407),
 ('kids', 0.0085828430043

In [69]:
word_coefficient_tuples = sorted(word_coefficient_tuples, key=lambda x:x[1], reverse=False)

In [70]:
word_coefficient_tuples

[('would', -0.05386014844520314),
 ('product', -0.041511033392108904),
 ('money', -0.038982037286487116),
 ('work', -0.03306951529475273),
 ('even', -0.030051249236035804),
 ('disappointed', -0.028978976142317068),
 ('get', -0.028711552980192574),
 ('back', -0.027742697230661334),
 ('return', -0.026592778462247283),
 ('monitor', -0.024482100545891724),
 ('waste', -0.02404274807115496),
 ('thought', -0.021394348543682485),
 ('could', -0.01984625666077721),
 ('tried', -0.018702371424325834),
 ('way', -0.018359460662945686),
 ('time', -0.018246193486087033),
 ('buy', -0.01773754399721805),
 ('item', -0.01713786701085479),
 ('returned', -0.016001798500102516),
 ('broke', -0.01553769895565389),
 ('better', -0.01504065897704339),
 ('plastic', -0.01497704490358794),
 ('reviews', -0.014866319449976982),
 ('cheap', -0.014709833465080665),
 ('thing', -0.013868727265297583),
 ('hard', -0.013756676731261401),
 ('first', -0.013213475301677043),
 ('never', -0.012969046546319292),
 ('something', -0.0